### ISSUE TITLE
Zero dependency (vanilla js)

### ISSUE THREAD

**Issue by abalter** [mathuo/dockview#172]
Does "zero dependency" mean it can run as a vanilla js library?

Is there an example of how to do that?

**Comment by mathuo** [comment]
Currently dockview is specifically a designed for use with React. Dockview does has zero dependencies but it does have a peer dependency on the react and react-dom libraries.

Although, the entire project is written in vanilla js and exposes a react layer on top for people to use. It would easier work in vanilla js if the react peer dependency could be isolated. Let me take a look at this and see if I can provide an example of using dockview using only vanilla js.

**Comment by mathuo** [comment]
I've published an experimental build to npm under the experimental tag [0.0.0-experimental-ff3f0b23-20230207](https://www.npmjs.com/package/dockview/v/0.0.0-experimental-ff3f0b23-20230207).

There are numerous issues with this still but I wanted to show where I was at on this. It's very reasonable to assume dockview can support Vanilla JS/TS since the majority of the library is written in plain TypeScript with the React components simply wrappers on top of the core logic.

The sandbox [here](https://codesandbox.io/s/dockview-vanilla-js-forked-rfurt0) example shows a "running example" (not necessarily a working example) written in plain TypeScript. As you will see there are issues:
1. The interface simply isn't clear. You need to implement the **IContentRenderer** interface to provide your own panel but this interface isn't "clean" enough for public use. I will need to work on cleaning this interface, making the purpose of the methods clearer and reducing the number of required methods to implement to a minimum.

> For example in the React version there is an implementation of this interface with the React world which you can see [here](https://github.com/mathuo/dockview/blob/master/packages/dockview/src/react/dockview/reactContentPart.ts)

2. Some of the required types in the TypeScript world are not exposed correctly which you will see as errors in the sandbox.

3. dockview has a peer dependency on react and react-dom. To circumvent this causing compliation issues (if you import anything from dockview you as a by-product will import things from react and react-dom) I've seperated and isolated the react code and you can avoid importing this section of the code through by importing from **dockview/dist/cjs/core** rather than **dockview** (which in itself is a big usability problem that needs fixing). To address this the library would probably need to be split into two seperate packages, one contains the core contents and another exposes only the react wrappers that has a peer dependency to the core package.

**Comment by abalter** [comment]
I wonder if something in the spirit of this would be possible:

```
<html>
<head>
    <link type="text/css" rel="stylesheet" href="link to dockview.css">
    <script type="text/javascript" src="cdn for jquery">
    <script type="text/javascript" src="cdn for react">
    <script type="text/javascript" src="link to a single file with no dependencies other than react and maybe jquery dockview.min.js">
<head>
<html>
    <body>
        <div class="dockview-div"></div>
        <script>
            dock = new DockView("dockview-div")
            dock
                .addPanel(title="Panel1", location="top-left", width=0.5, height=0.5)
                .addPanel(title = "Panel2", location="top-right", width=0.5)
                .addPanel(title = "Panel3", location='bottom', width=1.0)
        </script>
    <body>
<html>

```

Or, to follow an existing paradigm, something like this: https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxdockinglayout/jquery-docking-layout-getting-started.htm?search=

**Comment by mathuo** [comment]
Moving this under the Discussions section [here](https://github.com/mathuo/dockview/discussions/239)

**Comment by abalter** [comment]
Hi @mathuo. [This example](https://codesandbox.io/s/github/mathuo/dockview/tree/master/packages/docs/sandboxes/simple-dockview?file=/src/index.tsx:0-458) (linked to in the discussion referenced above) uses both react and typescript. Is it actually possible in vanilla JS?

_index.tsx_
```js
import { StrictMode } from 'react';
import * as ReactDOMClient from 'react-dom/client';
import './styles.css';
import 'dockview/dist/styles/dockview.css';

import App from './app';

const rootElement = document.getElementById('root');

if (rootElement) {
    const root = ReactDOMClient.createRoot(rootElement);

    root.render(
        <StrictMode>
            <div className="app">
                <App />
            </div>
        </StrictMode>
    );
}
```

**Comment by abalter** [comment]
I see now there is a drop-down on the example for a javascript version. However that still isn't vanilla javascript.

**Comment by mathuo** [comment]
> I see now there is a drop-down on the example for a javascript version. However that still isn't vanilla javascript.

What are you defining as vanilla javascript?

**Comment by abalter** [comment]
_index.html_
```
<html>
    <head>
        <script src="js/main_library.js"></script>
        <link rel="stylesheet" href="css/styles.css">
    </head>
    <body>
        <div id="the-div-for-the-app"></div>
        <script src="js/custom-script-for-myapp.js"></script>
    </body>
</html>
```

Here is a (really bad) web app that uses an [extensive and complex pure-javascript widget library](https://github.com/paulrosen/abcjs). I use the library by loading a [single javascript file](https://github.com/paulrosen/abcjs/blob/main/dist/abcjs-basic-min.js).

https://arielbalter.org/session-practice/

**Comment by abalter** [comment]
Overall, I like dock-view the best in terms of functionality and appearance. But there are a number of pure-js libraries that require only loading a single library file. Also, some are not FOSS, for example JQWidgets. Dock Spawn TS is a pure JS library (no react) but not something you can link to as a single file. 

- https://golden-layout.com/
- https://www.jqwidgets.com/jquery-widgets-documentation/documentation/jqxdockinglayout/jquery-docking-layout-getting-started.htm
- https://node-projects.github.io/dock-spawn-ts/#

**Comment by eclipse313** [comment]
I'm speaking for the Vue community here. It would be great if there was also a Vue version of this. Especially since dockview-core is not related to React, this should be possible in principle.

I've just had a look at the source code, but I'm struggling a bit with porting the React portal stuff to Vue.

Can anyone help?

**Comment by mathuo** [comment]
Moving discussion to [here](https://github.com/mathuo/dockview/issues/562)

@yoshiok @eclipse313
