### ISSUE TITLE
Popout group flow error

### ISSUE THREAD

**Issue by mathuo** [mathuo/dockview#797]
This is half-fixed as of 2.1.1 - 

When a panel or group goes from grid -> popout -> floating, Dockview used to crash. Now, dockview creates the floating group as expected. Nice!

But when a panel or group goes from floating -> popout -> floating, Dockview used to make a (bugged) empty floating group. Now Dockview throws an error, and the panel is closed.

Video attached. I can move this to a new issue if you'd prefer!

https://github.com/user-attachments/assets/7799d295-b19f-4ced-ae05-9408c9a6e2fd

_Originally posted by @zaxer2 in https://github.com/mathuo/dockview/issues/782#issuecomment-2557720596_

**Comment by mathuo** [comment]
@zaxer2 This should be fixed in `2.1.2`. Please do let me know if that works for you

**Comment by zaxer2** [comment]
> @zaxer2 This should be fixed in `2.1.4`. Please do let me know if that works for you

This fix looks great for Panels, individual panels are moving smooth as butter.

There is one remaining spot of weirdness regarding Groups in particular: if you make a Group into a Floating group -> then into a Popout group -> then back into a Floating group, Dockview still crashes. 

All other behavior seems normal though, as far as I can tell! 👍

https://github.com/user-attachments/assets/fa087431-7880-42b5-b45a-8f938ed0f4bb

**Comment by mathuo** [comment]
Amazing - I believe I've found this issue too. I will raise a PR and aim to release once tested. Thanks for all the work in finding this issues!

**Comment by zaxer2** [comment]
Of course! It's all stuff that's popped up naturally in my use case- documented to the best of my ability. Thanks for creating & maintaining such a useful tool! I'm awed by its versatility :)
